=== Repiteo/godot/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?><!-- dummy -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="keywords" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="value" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="inherits" use="optional" />
			<xs:attribute type="xs:string" name="api_type" use="optional" />
			<!-- deprecated -->
			<xs:attribute type="xs:float" name="version" use="optional" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<!-- /deprecated -->
			<xs:attribute type="xs:string" name="deprecated" use="optional" />
			<xs:attribute type="xs:string" name="experimental" use="optional" />
			<xs:attribute type="xs:string" name="keywords" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Repiteo/godot/doc/classes/TypeRef.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="TypeRef" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
	</brief_description>
	<description>
	</description>
	<tutorials>
	</tutorials>
	<constructors>
		<constructor name="TypeRef">
			<return type="TypeRef" />
			<description>
			</description>
		</constructor>
		<constructor name="TypeRef">
			<return type="TypeRef" />
			<param index="0" name="from" type="TypeRef" />
			<description>
			</description>
		</constructor>
		<constructor name="TypeRef">
			<return type="TypeRef" />
			<param index="0" name="type_struct" type="Array" />
			<description>
			</description>
		</constructor>
		<constructor name="TypeRef">
			<return type="TypeRef" />
			<param index="0" name="variant_type" type="int" />
			<param index="1" name="class_name" type="StringName" />
			<param index="2" name="script" type="Variant" />
			<param index="3" name="nested_types" type="Array" />
			<description>
			</description>
		</constructor>
	</constructors>
	<methods>
		<method name="from_builtin_type" qualifiers="static">
			<return type="TypeRef" />
			<param index="0" name="variant_type" type="int" />
			<description>
			</description>
		</method>
		<method name="from_native_type" qualifiers="static">
			<return type="TypeRef" />
			<param index="0" name="class_name" type="StringName" />
			<description>
			</description>
		</method>
		<method name="from_script_type" qualifiers="static">
			<return type="TypeRef" />
			<param index="0" name="script" type="Variant" />
			<description>
			</description>
		</method>
		<method name="get_builtin_type" qualifiers="const">
			<return type="int" />
			<description>
			</description>
		</method>
		<method name="get_native_type" qualifiers="const">
			<return type="StringName" />
			<description>
			</description>
		</method>
		<method name="get_nested_types" qualifiers="const">
			<return type="Array" />
			<description>
			</description>
		</method>
		<method name="get_script_type" qualifiers="const">
			<return type="Variant" />
			<description>
			</description>
		</method>
		<method name="has_nested_types" qualifiers="const">
			<return type="bool" />
			<description>
			</description>
		</method>
		<method name="hash" qualifiers="const">
			<return type="int" />
			<description>
			</description>
		</method>
	</methods>
</class>

=== Repiteo/godot/doc/classes/JSON.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="JSON" inherits="Resource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Helper class for creating and parsing JSON data.
	</brief_description>
	<description>
		The [JSON] class enables all data types to be converted to and from a JSON string. This is useful for serializing data, e.g. to save to a file or send over the network.
		[method stringify] is used to convert any data type into a JSON string.
		[method parse] is used to convert any existing JSON data into a [Variant] that can be used within Godot. If successfully parsed, use [member data] to retrieve the [Variant], and use [method @GlobalScope.typeof] to check if the Variant's type is what you expect. JSON Objects are converted into a [Dictionary], but JSON data can be used to store [Array]s, numbers, [String]s and even just a boolean.
		[codeblock]
		var data_to_send = ["a", "b", "c"]
		var json_string = JSON.stringify(data_to_send)
		# Save data
		# ...
		# Retrieve data
		var json = JSON.new()
		var error = json.parse(json_string)
		if error == OK:
			var data_received = json.data
			if typeof(data_received) == TYPE_ARRAY:
				print(data_received) # Prints the array.
			else:
				print("Unexpected data")
		else:
			print("JSON Parse Error: ", json.get_error_message(), " in ", json_string, " at line ", json.get_error_line())
		[/codeblock]
		Alternatively, you can parse strings using the static [method parse_string] method, but it doesn't handle errors.
		[codeblock]
		var data = JSON.parse_string(json_string) # Returns null if parsing failed.
		[/codeblock]
		[b]Note:[/b] Both parse methods do not fully comply with the JSON specification:
		- Trailing commas in arrays or objects are ignored, instead of causing a parser error.
		- New line and tab characters are accepted in string literals, and are treated like their corresponding escape sequences [code]\n[/code] and [code]\t[/code].
		- Numbers are parsed using [method String.to_float] which is generally more lax than the JSON specification.
		- Certain errors, such as invalid Unicode sequences, do not cause a parser error. Instead, the string is cleaned up and an error is logged to the console.
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="from_native" qualifiers="static">
			<return type="Variant" />
			<param index="0" name="variant" type="Variant" />
			<param index="1" name="full_objects" type="bool" default="false" />
			<description>
				Converts a native engine type to a JSON-compliant value.
				By default, objects are ignored for security reasons, unless [param full_objects] is [code]true[/code].
				You can convert a native value to a JSON string like this:
				[codeblock]
				func encode_data(value, full_objects = false):
					return JSON.stringify(JSON.from_native(value, full_objects))
				[/codeblock]
			</description>
		</method>
		<method name="get_error_line" qualifiers="const">
			<return type="int" />
			<description>
				Returns [code]0[/code] if the last call to [method parse] was successful, or the line number where the parse failed.
			</description>
		</method>
		<method name="get_error_message" qualifiers="const">
			<return type="String" />
			<description>
				Returns an empty string if the last call to [method parse] was successful, or the error message if it failed.
			</description>
		</method>
		<method name="get_parsed_text" qualifiers="const">
			<return type="String" />
			<description>
				Return the text parsed by [method parse] (requires passing [code]keep_text[/code] to [method parse]).
			</description>
		</method>
		<method name="parse">
			<return type="int" enum="Error" />
			<param index="0" name="json_text" type="String" />
			<param index="1" name="keep_text" type="bool" default="false" />
			<description>
				Attempts to parse the [param json_text] provided.
				Returns an [enum Error]. If the parse was successful, it returns [constant OK] and the result can be retrieved using [member data]. If unsuccessful, use [method get_error_line] and [method get_error_message] to identify the source of the failure.
				Non-static variant of [method parse_string], if you want custom error handling.
				The optional [param keep_text] argument instructs the parser to keep a copy of the original text. This text can be obtained later by using the [method get_parsed_text] function and is used when saving the resource (instead of generating new text from [member data]).
			</description>
		</method>
		<method name="parse_string" qualifiers="static">
			<return type="Variant" />
			<param index="0" name="json_string" type="String" />
			<description>
				Attempts to parse the [param json_string] provided and returns the parsed data. Returns [code]null[/code] if parse failed.
			</description>
		</method>
		<method name="stringify" qualifiers="static">
			<return type="String" />
			<param index="0" name="data" type="Variant" />
			<param index="1" name="indent" type="String" default="&quot;&quot;" />
			<param index="2" name="sort_keys" type="bool" default="true" />
			<param index="3" name="full_precision" type="bool" default="false" />
			<description>
				Converts a [Variant] var to JSON text and returns the result. Useful for serializing data to store or send over the network.
				[b]Note:[/b] The JSON specification does not define integer or float types, but only a [i]number[/i] type. Therefore, converting a Variant to JSON text will convert all numerical values to [float] types.
				[b]Note:[/b] If [param full_precision] is [code]true[/code], when stringifying floats, the unreliable digits are stringified in addition to the reliable digits to guarantee exact decoding.
				The [param indent] parameter controls if and how something is indented; its contents will be used where there should be an indent in the output. Even spaces like [code]"   "[/code] will work. [code]\t[/code] and [code]\n[/code] can also be used for a tab indent, or to make a newline for each indent respectively.
				[b]Warning:[/b] The JSON specification only permits finite numbers. Any instances of [constant @GDScript.INF], -[constant @GDScript.INF], or [constant @GDScript.NAN] will be converted to [code]null[/code]. If you rely on these constants, you must pass through [method from_native] first.
				[b]Example output:[/b]
				[codeblock]
				## JSON.stringify(my_dictionary)
				{"name":"my_dictionary","version":"1.0.0","entities":[{"name":"entity_0","value":"value_0"},{"name":"entity_1","value":"value_1"}]}

				## JSON.stringify(my_dictionary, "\t")
				{
					"name": "my_dictionary",
					"version": "1.0.0",
					"entities": [
						{
							"name": "entity_0",
							"value": "value_0"
						},
						{
							"name": "entity_1",
							"value": "value_1"
						}
					]
				}

				## JSON.stringify(my_dictionary, "...")
				{
				..."name": "my_dictionary",
				..."version": "1.0.0",
				..."entities": [
				......{
				........."name": "entity_0",
				........."value": "value_0"
				......},
				......{
				........."name": "entity_1",
				........."value": "value_1"
				......}
				...]
				}
				[/codeblock]
			</description>
		</method>
		<method name="to_native" qualifiers="static">
			<return type="Variant" />
			<param index="0" name="json" type="Variant" />
			<param index="1" name="allow_objects" type="bool" default="false" />
			<description>
				Converts a JSON-compliant value that was created with [method from_native] back to native engine types.
				By default, objects are ignored for security reasons, unless [param allow_objects] is [code]true[/code].
				You can convert a JSON string back to a native value like this:
				[codeblock]
				func decode_data(string, allow_objects = false):
					return JSON.to_native(JSON.parse_string(string), allow_objects)
				[/codeblock]
			</description>
		</method>
	</methods>
	<members>
		<member name="data" type="Variant" setter="set_data" getter="get_data" default="null">
			Contains the parsed JSON data in [Variant] form.
		</member>
	</members>
</class>

=== Repiteo/godot/doc/classes/InputHandler.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="InputHandler" inherits="RefCounted" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
	</brief_description>
	<description>
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="_get_name" qualifiers="virtual const">
			<return type="String" />
			<description>
			</description>
		</method>
		<method name="claim_device">
			<return type="int" />
			<description>
			</description>
		</method>
		<method name="get_name" qualifiers="const">
			<return type="String" />
			<description>
			</description>
		</method>
		<method name="release_device">
			<return type="void" />
			<param index="0" name="device" type="int" />
			<description>
			</description>
		</method>
		<method name="set_device_axis">
			<return type="void" />
			<param index="0" name="device" type="int" />
			<param index="1" name="axis" type="int" enum="JoyAxis" />
			<param index="2" name="value" type="float" />
			<description>
			</description>
		</method>
		<method name="set_device_button">
			<return type="void" />
			<param index="0" name="device" type="int" />
			<param index="1" name="button" type="int" enum="JoyButton" />
			<param index="2" name="pressed" type="bool" />
			<description>
			</description>
		</method>
	</methods>
</class>

=== Repiteo/godot/doc/classes/USBAccess.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="USBAccess" inherits="RefCounted" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
	</brief_description>
	<description>
	</description>
	<tutorials>
	</tutorials>
	<methods>
		<method name="close">
			<return type="void" />
			<description>
			</description>
		</method>
		<method name="get_open_error" qualifiers="static">
			<return type="int" enum="Error" />
			<description>
			</description>
		</method>
		<method name="get_ports" qualifiers="static">
			<return type="Dictionary[]" />
			<description>
			</description>
		</method>
		<method name="open" qualifiers="static">
			<return type="USBAccess" />
			<param index="0" name="vendor_id" type="int" />
			<param index="1" name="product_id" type="int" />
			<description>
			</description>
		</method>
	</methods>
	<members>
		<member name="product_id" type="int" setter="" getter="get_product_id">
		</member>
		<member name="vendor_id" type="int" setter="" getter="get_vendor_id">
		</member>
	</members>
</class>

=== Repiteo/godot/doc/classes/Benchmark.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="Benchmark" inherits="RefCounted" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
	</brief_description>
	<description>
	</description>
	<tutorials>
	</tutorials>
	<members>
		<member name="benchmark_time" type="int" setter="set_benchmark_time" getter="get_benchmark_time" default="5000000">
		</member>
		<member name="test_idle" type="bool" setter="set_test_idle" getter="get_test_idle" default="false">
		</member>
		<member name="test_physics" type="bool" setter="set_test_physics" getter="get_test_physics" default="false">
		</member>
		<member name="test_render_cpu" type="bool" setter="set_test_render_cpu" getter="get_test_render_cpu" default="false">
		</member>
		<member name="test_render_gpu" type="bool" setter="set_test_render_gpu" getter="get_test_render_gpu" default="false">
		</member>
	</members>
</class>
